apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: k8s-storage
    path: /srv/nfs/k8s/jenkins
  persistentVolumeReclaimPolicy: Retain